# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from verizon.api_helper import APIHelper
from verizon.models.account_share_filter_criteria_1 import AccountShareFilterCriteria1


class AccountShareFilterCriteria(object):

    """Implementation of the 'accountShareFilterCriteria' model.

    Attributes:
        filter_criteria (AccountShareFilterCriteria1): The model property of
            type AccountShareFilterCriteria1.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "filter_criteria": 'filterCriteria'
    }

    _optionals = [
        'filter_criteria',
    ]

    def __init__(self,
                 filter_criteria=APIHelper.SKIP):
        """Constructor for the AccountShareFilterCriteria class"""

        # Initialize members of the class
        if filter_criteria is not APIHelper.SKIP:
            self.filter_criteria = filter_criteria 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        filter_criteria = AccountShareFilterCriteria1.from_dictionary(dictionary.get('filterCriteria')) if 'filterCriteria' in dictionary.keys() else APIHelper.SKIP
        # Return an object of this model
        return cls(filter_criteria)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'filter_criteria={(self.filter_criteria if hasattr(self, "filter_criteria") else None)!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'filter_criteria={(self.filter_criteria if hasattr(self, "filter_criteria") else None)!s})')
