# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from verizon.api_helper import APIHelper
from verizon.models.account_share_price_plan_trigger import AccountSharePricePlanTrigger
from verizon.models.notificationarray import Notificationarray


class AccountShareUpdateTriggerRequest(object):

    """Implementation of the 'accountShareUpdateTriggerRequest' model.

    Attributes:
        trigger_id (str): The system assigned UUID of the trigger
        trigger_name (str): The user defined name of the trigger
        ecpd_id (str): The Enterprise Customer Profile Database ID
        trigger_category (TriggerCategoryEnum): The type of trigger being
            created or modified
        price_plan_trigger (AccountSharePricePlanTrigger): The model property
            of type AccountSharePricePlanTrigger.
        notification (Notificationarray): The model property of type
            Notificationarray.
        active (ActiveEnum): A flag to indicate of the trigger is active,
            true, or not, false

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "trigger_id": 'triggerId',
        "trigger_name": 'triggerName',
        "ecpd_id": 'ecpdId',
        "trigger_category": 'triggerCategory',
        "price_plan_trigger": 'pricePlanTrigger',
        "notification": 'notification',
        "active": 'active'
    }

    _optionals = [
        'trigger_id',
        'trigger_name',
        'ecpd_id',
        'trigger_category',
        'price_plan_trigger',
        'notification',
        'active',
    ]

    def __init__(self,
                 trigger_id=APIHelper.SKIP,
                 trigger_name=APIHelper.SKIP,
                 ecpd_id=APIHelper.SKIP,
                 trigger_category=APIHelper.SKIP,
                 price_plan_trigger=APIHelper.SKIP,
                 notification=APIHelper.SKIP,
                 active=APIHelper.SKIP):
        """Constructor for the AccountShareUpdateTriggerRequest class"""

        # Initialize members of the class
        if trigger_id is not APIHelper.SKIP:
            self.trigger_id = trigger_id 
        if trigger_name is not APIHelper.SKIP:
            self.trigger_name = trigger_name 
        if ecpd_id is not APIHelper.SKIP:
            self.ecpd_id = ecpd_id 
        if trigger_category is not APIHelper.SKIP:
            self.trigger_category = trigger_category 
        if price_plan_trigger is not APIHelper.SKIP:
            self.price_plan_trigger = price_plan_trigger 
        if notification is not APIHelper.SKIP:
            self.notification = notification 
        if active is not APIHelper.SKIP:
            self.active = active 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        trigger_id = dictionary.get("triggerId") if dictionary.get("triggerId") else APIHelper.SKIP
        trigger_name = dictionary.get("triggerName") if dictionary.get("triggerName") else APIHelper.SKIP
        ecpd_id = dictionary.get("ecpdId") if dictionary.get("ecpdId") else APIHelper.SKIP
        trigger_category = dictionary.get("triggerCategory") if dictionary.get("triggerCategory") else APIHelper.SKIP
        price_plan_trigger = AccountSharePricePlanTrigger.from_dictionary(dictionary.get('pricePlanTrigger')) if 'pricePlanTrigger' in dictionary.keys() else APIHelper.SKIP
        notification = Notificationarray.from_dictionary(dictionary.get('notification')) if 'notification' in dictionary.keys() else APIHelper.SKIP
        active = dictionary.get("active") if dictionary.get("active") else APIHelper.SKIP
        # Return an object of this model
        return cls(trigger_id,
                   trigger_name,
                   ecpd_id,
                   trigger_category,
                   price_plan_trigger,
                   notification,
                   active)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'trigger_id={(self.trigger_id if hasattr(self, "trigger_id") else None)!r}, '
                f'trigger_name={(self.trigger_name if hasattr(self, "trigger_name") else None)!r}, '
                f'ecpd_id={(self.ecpd_id if hasattr(self, "ecpd_id") else None)!r}, '
                f'trigger_category={(self.trigger_category if hasattr(self, "trigger_category") else None)!r}, '
                f'price_plan_trigger={(self.price_plan_trigger if hasattr(self, "price_plan_trigger") else None)!r}, '
                f'notification={(self.notification if hasattr(self, "notification") else None)!r}, '
                f'active={(self.active if hasattr(self, "active") else None)!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'trigger_id={(self.trigger_id if hasattr(self, "trigger_id") else None)!s}, '
                f'trigger_name={(self.trigger_name if hasattr(self, "trigger_name") else None)!s}, '
                f'ecpd_id={(self.ecpd_id if hasattr(self, "ecpd_id") else None)!s}, '
                f'trigger_category={(self.trigger_category if hasattr(self, "trigger_category") else None)!s}, '
                f'price_plan_trigger={(self.price_plan_trigger if hasattr(self, "price_plan_trigger") else None)!s}, '
                f'notification={(self.notification if hasattr(self, "notification") else None)!s}, '
                f'active={(self.active if hasattr(self, "active") else None)!s})')
