# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from verizon.api_helper import APIHelper
from verizon.models.change_plan_details import ChangePlanDetails
from verizon.models.suspenddetailsobject import Suspenddetailsobject


class Actionobject(object):

    """Implementation of the 'actionobject' model.

    Attributes:
        suspend (bool): The model property of type bool.
        suspend_details (Suspenddetailsobject): The model property of type
            Suspenddetailsobject.
        change_plan (bool): a flag to set if the trigger changes service
            plans, true, or not, false
        change_plan_details (ChangePlanDetails): The service plan code to
            switch to

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "suspend": 'suspend',
        "suspend_details": 'suspendDetails',
        "change_plan": 'changePlan',
        "change_plan_details": 'changePlanDetails'
    }

    _optionals = [
        'suspend',
        'suspend_details',
        'change_plan',
        'change_plan_details',
    ]

    def __init__(self,
                 suspend=APIHelper.SKIP,
                 suspend_details=APIHelper.SKIP,
                 change_plan=APIHelper.SKIP,
                 change_plan_details=APIHelper.SKIP):
        """Constructor for the Actionobject class"""

        # Initialize members of the class
        if suspend is not APIHelper.SKIP:
            self.suspend = suspend 
        if suspend_details is not APIHelper.SKIP:
            self.suspend_details = suspend_details 
        if change_plan is not APIHelper.SKIP:
            self.change_plan = change_plan 
        if change_plan_details is not APIHelper.SKIP:
            self.change_plan_details = change_plan_details 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        suspend = dictionary.get("suspend") if "suspend" in dictionary.keys() else APIHelper.SKIP
        suspend_details = Suspenddetailsobject.from_dictionary(dictionary.get('suspendDetails')) if 'suspendDetails' in dictionary.keys() else APIHelper.SKIP
        change_plan = dictionary.get("changePlan") if "changePlan" in dictionary.keys() else APIHelper.SKIP
        change_plan_details = ChangePlanDetails.from_dictionary(dictionary.get('changePlanDetails')) if 'changePlanDetails' in dictionary.keys() else APIHelper.SKIP
        # Return an object of this model
        return cls(suspend,
                   suspend_details,
                   change_plan,
                   change_plan_details)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'suspend={(self.suspend if hasattr(self, "suspend") else None)!r}, '
                f'suspend_details={(self.suspend_details if hasattr(self, "suspend_details") else None)!r}, '
                f'change_plan={(self.change_plan if hasattr(self, "change_plan") else None)!r}, '
                f'change_plan_details={(self.change_plan_details if hasattr(self, "change_plan_details") else None)!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'suspend={(self.suspend if hasattr(self, "suspend") else None)!s}, '
                f'suspend_details={(self.suspend_details if hasattr(self, "suspend_details") else None)!s}, '
                f'change_plan={(self.change_plan if hasattr(self, "change_plan") else None)!s}, '
                f'change_plan_details={(self.change_plan_details if hasattr(self, "change_plan_details") else None)!s})')
