# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class AttributeIdentifierEnum(object):

    """Implementation of the 'AttributeIdentifier' enum.

    Attribute identifier.

    Attributes:
        NETWORK_BEARER: The enum member of type str.
        RADIO_SIGNAL_STRENGTH: The enum member of type str.
        LINK_QUALITY: The enum member of type str.
        CELL_ID: The enum member of type str.
        MANUFACTURER: The enum member of type str.

    """
    NETWORK_BEARER = 'NETWORK_BEARER'

    RADIO_SIGNAL_STRENGTH = 'RADIO_SIGNAL_STRENGTH'

    LINK_QUALITY = 'LINK_QUALITY'

    CELL_ID = 'CELL_ID'

    MANUFACTURER = 'MANUFACTURER'

