# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ComparitorEnum(object):

    """Implementation of the 'Comparitor' enum.

    The boolean of the comparison. `gt` is Greater Than, `lt` is Less Than and
    `eq` is Equal To

    Attributes:
        GT: The enum member of type str.
        LT: The enum member of type str.
        EQ: The enum member of type str.

    """
    GT = 'gt'

    LT = 'lt'

    EQ = 'eq'

