# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from verizon.api_helper import APIHelper
from verizon.models.allowance_threshold import AllowanceThreshold


class ConditionObjectCall(object):

    """Implementation of the 'conditionObjectCall' model.

    Attributes:
        condition_type (ConditionTypeEnum): The condition type being monitored
        comparitor (ComparitorEnum): The boolean of the comparison. `gt` is
            Greater Than, `lt` is Less Than and `eq` is Equal To
        threshold (int): The threshold value the trigger monitors for
        threshold_unit (ThresholdUnitEnum): The units of the threshold. This
            can be KB, Kilobits, MB, Megabits, or GB, Gigabits
        cycle_type (RulesCycleTypeEnum): The interval to monitor for the
            threshold. This can be Daily, Weekly or Monthly
        allowance_threshold (AllowanceThreshold): The model property of type
            AllowanceThreshold.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "condition_type": 'conditionType',
        "comparitor": 'comparitor',
        "threshold": 'threshold',
        "threshold_unit": 'thresholdUnit',
        "cycle_type": 'cycleType',
        "allowance_threshold": 'allowanceThreshold'
    }

    _optionals = [
        'condition_type',
        'comparitor',
        'threshold',
        'threshold_unit',
        'cycle_type',
        'allowance_threshold',
    ]

    def __init__(self,
                 condition_type=APIHelper.SKIP,
                 comparitor=APIHelper.SKIP,
                 threshold=APIHelper.SKIP,
                 threshold_unit=APIHelper.SKIP,
                 cycle_type=APIHelper.SKIP,
                 allowance_threshold=APIHelper.SKIP):
        """Constructor for the ConditionObjectCall class"""

        # Initialize members of the class
        if condition_type is not APIHelper.SKIP:
            self.condition_type = condition_type 
        if comparitor is not APIHelper.SKIP:
            self.comparitor = comparitor 
        if threshold is not APIHelper.SKIP:
            self.threshold = threshold 
        if threshold_unit is not APIHelper.SKIP:
            self.threshold_unit = threshold_unit 
        if cycle_type is not APIHelper.SKIP:
            self.cycle_type = cycle_type 
        if allowance_threshold is not APIHelper.SKIP:
            self.allowance_threshold = allowance_threshold 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        condition_type = dictionary.get("conditionType") if dictionary.get("conditionType") else APIHelper.SKIP
        comparitor = dictionary.get("comparitor") if dictionary.get("comparitor") else APIHelper.SKIP
        threshold = dictionary.get("threshold") if dictionary.get("threshold") else APIHelper.SKIP
        threshold_unit = dictionary.get("thresholdUnit") if dictionary.get("thresholdUnit") else APIHelper.SKIP
        cycle_type = dictionary.get("cycleType") if dictionary.get("cycleType") else APIHelper.SKIP
        allowance_threshold = AllowanceThreshold.from_dictionary(dictionary.get('allowanceThreshold')) if 'allowanceThreshold' in dictionary.keys() else APIHelper.SKIP
        # Return an object of this model
        return cls(condition_type,
                   comparitor,
                   threshold,
                   threshold_unit,
                   cycle_type,
                   allowance_threshold)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'condition_type={(self.condition_type if hasattr(self, "condition_type") else None)!r}, '
                f'comparitor={(self.comparitor if hasattr(self, "comparitor") else None)!r}, '
                f'threshold={(self.threshold if hasattr(self, "threshold") else None)!r}, '
                f'threshold_unit={(self.threshold_unit if hasattr(self, "threshold_unit") else None)!r}, '
                f'cycle_type={(self.cycle_type if hasattr(self, "cycle_type") else None)!r}, '
                f'allowance_threshold={(self.allowance_threshold if hasattr(self, "allowance_threshold") else None)!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'condition_type={(self.condition_type if hasattr(self, "condition_type") else None)!s}, '
                f'comparitor={(self.comparitor if hasattr(self, "comparitor") else None)!s}, '
                f'threshold={(self.threshold if hasattr(self, "threshold") else None)!s}, '
                f'threshold_unit={(self.threshold_unit if hasattr(self, "threshold_unit") else None)!s}, '
                f'cycle_type={(self.cycle_type if hasattr(self, "cycle_type") else None)!s}, '
                f'allowance_threshold={(self.allowance_threshold if hasattr(self, "allowance_threshold") else None)!s})')
