# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ConnectionResponse(object):

    """Implementation of the 'ConnectionResponse' model.

    response for /clients/connection

    Attributes:
        mqtt_url (str): The model property of type str.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "mqtt_url": 'MqttURL'
    }

    def __init__(self,
                 mqtt_url=None):
        """Constructor for the ConnectionResponse class"""

        # Initialize members of the class
        self.mqtt_url = mqtt_url 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        mqtt_url = dictionary.get("MqttURL") if dictionary.get("MqttURL") else None
        # Return an object of this model
        return cls(mqtt_url)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'mqtt_url={self.mqtt_url!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'mqtt_url={self.mqtt_url!s})')
