# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from verizon.api_helper import APIHelper


class ConsentTransactionID(object):

    """Implementation of the 'ConsentTransactionID' model.

    The transaction ID of the request that you want to cancel, from the POST
    /devicelocations synchronus response.

    Attributes:
        transaction_id (str): The model property of type str.
        status (str): The model property of type str.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "transaction_id": 'transactionId',
        "status": 'status'
    }

    _optionals = [
        'transaction_id',
        'status',
    ]

    def __init__(self,
                 transaction_id=APIHelper.SKIP,
                 status=APIHelper.SKIP):
        """Constructor for the ConsentTransactionID class"""

        # Initialize members of the class
        if transaction_id is not APIHelper.SKIP:
            self.transaction_id = transaction_id 
        if status is not APIHelper.SKIP:
            self.status = status 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        transaction_id = dictionary.get("transactionId") if dictionary.get("transactionId") else APIHelper.SKIP
        status = dictionary.get("status") if dictionary.get("status") else APIHelper.SKIP
        # Return an object of this model
        return cls(transaction_id,
                   status)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'transaction_id={(self.transaction_id if hasattr(self, "transaction_id") else None)!r}, '
                f'status={(self.status if hasattr(self, "status") else None)!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'transaction_id={(self.transaction_id if hasattr(self, "transaction_id") else None)!s}, '
                f'status={(self.status if hasattr(self, "status") else None)!s})')
