# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class CycleTypeEnum(object):

    """Implementation of the 'CycleType' enum.

    Attributes:
        CYCLEONE: The enum member of type str.
        CYCLETWO: The enum member of type str.

    """
    CYCLEONE = 'cycleone'

    CYCLETWO = 'cycletwo'

