# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from verizon.api_helper import APIHelper
from verizon.models.account_group_share_individual_1 import AccountGroupShareIndividual1
from verizon.models.account_level_filter import AccountLevelFilter
from verizon.models.allowance_threshold import AllowanceThreshold
from verizon.models.device_group_filter_criteria import DeviceGroupFilterCriteria
from verizon.models.rateplantype_2_condition import Rateplantype2Condition


class DataTrigger5(object):

    """Implementation of the 'DataTrigger5' model.

    Attributes:
        filter_criteria (AccountLevelFilter): The model property of type
            AccountLevelFilter.
        condition (Rateplantype2Condition): The model property of type
            Rateplantype2Condition.
        action (AccountLevelActionEnum): The action taken when trigger
            conditions are met
        condition_type (ConditionTypeEnum): The condition type being monitored
        comparitor (ComparitorEnum): The boolean of the comparison. `gt` is
            Greater Than, `lt` is Less Than and `eq` is Equal To
        threshold (int): The threshold value the trigger monitors for
        threshold_unit (ThresholdUnitEnum): The units of the threshold. This
            can be KB, Kilobits, MB, Megabits, or GB, Gigabits
        cycle_type (RulesCycleTypeEnum): The interval to monitor for the
            threshold. This can be Daily, Weekly or Monthly
        allowance_threshold (AllowanceThreshold): The model property of type
            AllowanceThreshold.
        device_group (DeviceGroupFilterCriteria): The model property of type
            DeviceGroupFilterCriteria.
        account_group_share (AccountGroupShareIndividual1): The model property
            of type AccountGroupShareIndividual1.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "filter_criteria": 'filterCriteria',
        "condition": 'condition',
        "action": 'action',
        "condition_type": 'conditionType',
        "comparitor": 'comparitor',
        "threshold": 'threshold',
        "threshold_unit": 'thresholdUnit',
        "cycle_type": 'cycleType',
        "allowance_threshold": 'allowanceThreshold',
        "device_group": 'deviceGroup',
        "account_group_share": 'accountGroupShare'
    }

    _optionals = [
        'filter_criteria',
        'condition',
        'action',
        'condition_type',
        'comparitor',
        'threshold',
        'threshold_unit',
        'cycle_type',
        'allowance_threshold',
        'device_group',
        'account_group_share',
    ]

    def __init__(self,
                 filter_criteria=APIHelper.SKIP,
                 condition=APIHelper.SKIP,
                 action=APIHelper.SKIP,
                 condition_type=APIHelper.SKIP,
                 comparitor=APIHelper.SKIP,
                 threshold=APIHelper.SKIP,
                 threshold_unit=APIHelper.SKIP,
                 cycle_type=APIHelper.SKIP,
                 allowance_threshold=APIHelper.SKIP,
                 device_group=APIHelper.SKIP,
                 account_group_share=APIHelper.SKIP):
        """Constructor for the DataTrigger5 class"""

        # Initialize members of the class
        if filter_criteria is not APIHelper.SKIP:
            self.filter_criteria = filter_criteria 
        if condition is not APIHelper.SKIP:
            self.condition = condition 
        if action is not APIHelper.SKIP:
            self.action = action 
        if condition_type is not APIHelper.SKIP:
            self.condition_type = condition_type 
        if comparitor is not APIHelper.SKIP:
            self.comparitor = comparitor 
        if threshold is not APIHelper.SKIP:
            self.threshold = threshold 
        if threshold_unit is not APIHelper.SKIP:
            self.threshold_unit = threshold_unit 
        if cycle_type is not APIHelper.SKIP:
            self.cycle_type = cycle_type 
        if allowance_threshold is not APIHelper.SKIP:
            self.allowance_threshold = allowance_threshold 
        if device_group is not APIHelper.SKIP:
            self.device_group = device_group 
        if account_group_share is not APIHelper.SKIP:
            self.account_group_share = account_group_share 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        filter_criteria = AccountLevelFilter.from_dictionary(dictionary.get('filterCriteria')) if 'filterCriteria' in dictionary.keys() else APIHelper.SKIP
        condition = Rateplantype2Condition.from_dictionary(dictionary.get('condition')) if 'condition' in dictionary.keys() else APIHelper.SKIP
        action = dictionary.get("action") if dictionary.get("action") else APIHelper.SKIP
        condition_type = dictionary.get("conditionType") if dictionary.get("conditionType") else APIHelper.SKIP
        comparitor = dictionary.get("comparitor") if dictionary.get("comparitor") else APIHelper.SKIP
        threshold = dictionary.get("threshold") if dictionary.get("threshold") else APIHelper.SKIP
        threshold_unit = dictionary.get("thresholdUnit") if dictionary.get("thresholdUnit") else APIHelper.SKIP
        cycle_type = dictionary.get("cycleType") if dictionary.get("cycleType") else APIHelper.SKIP
        allowance_threshold = AllowanceThreshold.from_dictionary(dictionary.get('allowanceThreshold')) if 'allowanceThreshold' in dictionary.keys() else APIHelper.SKIP
        device_group = DeviceGroupFilterCriteria.from_dictionary(dictionary.get('deviceGroup')) if 'deviceGroup' in dictionary.keys() else APIHelper.SKIP
        account_group_share = AccountGroupShareIndividual1.from_dictionary(dictionary.get('accountGroupShare')) if 'accountGroupShare' in dictionary.keys() else APIHelper.SKIP
        # Return an object of this model
        return cls(filter_criteria,
                   condition,
                   action,
                   condition_type,
                   comparitor,
                   threshold,
                   threshold_unit,
                   cycle_type,
                   allowance_threshold,
                   device_group,
                   account_group_share)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'filter_criteria={(self.filter_criteria if hasattr(self, "filter_criteria") else None)!r}, '
                f'condition={(self.condition if hasattr(self, "condition") else None)!r}, '
                f'action={(self.action if hasattr(self, "action") else None)!r}, '
                f'condition_type={(self.condition_type if hasattr(self, "condition_type") else None)!r}, '
                f'comparitor={(self.comparitor if hasattr(self, "comparitor") else None)!r}, '
                f'threshold={(self.threshold if hasattr(self, "threshold") else None)!r}, '
                f'threshold_unit={(self.threshold_unit if hasattr(self, "threshold_unit") else None)!r}, '
                f'cycle_type={(self.cycle_type if hasattr(self, "cycle_type") else None)!r}, '
                f'allowance_threshold={(self.allowance_threshold if hasattr(self, "allowance_threshold") else None)!r}, '
                f'device_group={(self.device_group if hasattr(self, "device_group") else None)!r}, '
                f'account_group_share={(self.account_group_share if hasattr(self, "account_group_share") else None)!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'filter_criteria={(self.filter_criteria if hasattr(self, "filter_criteria") else None)!s}, '
                f'condition={(self.condition if hasattr(self, "condition") else None)!s}, '
                f'action={(self.action if hasattr(self, "action") else None)!s}, '
                f'condition_type={(self.condition_type if hasattr(self, "condition_type") else None)!s}, '
                f'comparitor={(self.comparitor if hasattr(self, "comparitor") else None)!s}, '
                f'threshold={(self.threshold if hasattr(self, "threshold") else None)!s}, '
                f'threshold_unit={(self.threshold_unit if hasattr(self, "threshold_unit") else None)!s}, '
                f'cycle_type={(self.cycle_type if hasattr(self, "cycle_type") else None)!s}, '
                f'allowance_threshold={(self.allowance_threshold if hasattr(self, "allowance_threshold") else None)!s}, '
                f'device_group={(self.device_group if hasattr(self, "device_group") else None)!s}, '
                f'account_group_share={(self.account_group_share if hasattr(self, "account_group_share") else None)!s})')
