# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from verizon.api_helper import APIHelper


class DeviceRole(object):

    """Implementation of the 'DeviceRole' model.

    The access rule (DeviceRole object) defines this topics the application or
    device can publish or subscribe to. It also defines how many parallel
    subscriptions one device or applications can have and how fast it can
    publish messages.

    Attributes:
        name (str): The unique name of the access rule.
        subscribe_limit (int): The maximum number of subscriptions that one
            application or device can make.
        publish_rate_limit (int): The maximum rate that one application or
            device can publish messages per seconds.
        publish (List[str]): The topics or topic patterns that the application
            or device is allowed to publish messages.
        subscribe (List[str]): The topics or topic patterns that the
            application or device is allowed to subscribe to.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "name": 'name',
        "subscribe_limit": 'subscribeLimit',
        "publish_rate_limit": 'publishRateLimit',
        "publish": 'publish',
        "subscribe": 'subscribe'
    }

    _optionals = [
        'subscribe_limit',
        'publish_rate_limit',
        'publish',
        'subscribe',
    ]

    def __init__(self,
                 name=None,
                 subscribe_limit=50,
                 publish_rate_limit=15,
                 publish=APIHelper.SKIP,
                 subscribe=APIHelper.SKIP):
        """Constructor for the DeviceRole class"""

        # Initialize members of the class
        self.name = name 
        self.subscribe_limit = subscribe_limit 
        self.publish_rate_limit = publish_rate_limit 
        if publish is not APIHelper.SKIP:
            self.publish = publish 
        if subscribe is not APIHelper.SKIP:
            self.subscribe = subscribe 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        name = dictionary.get("name") if dictionary.get("name") else None
        subscribe_limit = dictionary.get("subscribeLimit") if dictionary.get("subscribeLimit") else 50
        publish_rate_limit = dictionary.get("publishRateLimit") if dictionary.get("publishRateLimit") else 15
        publish = dictionary.get("publish") if dictionary.get("publish") else APIHelper.SKIP
        subscribe = dictionary.get("subscribe") if dictionary.get("subscribe") else APIHelper.SKIP
        # Return an object of this model
        return cls(name,
                   subscribe_limit,
                   publish_rate_limit,
                   publish,
                   subscribe)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'name={self.name!r}, '
                f'subscribe_limit={(self.subscribe_limit if hasattr(self, "subscribe_limit") else None)!r}, '
                f'publish_rate_limit={(self.publish_rate_limit if hasattr(self, "publish_rate_limit") else None)!r}, '
                f'publish={(self.publish if hasattr(self, "publish") else None)!r}, '
                f'subscribe={(self.subscribe if hasattr(self, "subscribe") else None)!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'name={self.name!s}, '
                f'subscribe_limit={(self.subscribe_limit if hasattr(self, "subscribe_limit") else None)!s}, '
                f'publish_rate_limit={(self.publish_rate_limit if hasattr(self, "publish_rate_limit") else None)!s}, '
                f'publish={(self.publish if hasattr(self, "publish") else None)!s}, '
                f'subscribe={(self.subscribe if hasattr(self, "subscribe") else None)!s})')
