# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from verizon.api_helper import APIHelper
from verizon.models.data_trigger_2 import DataTrigger2
from verizon.models.notificationarray import Notificationarray


class DeviceLevelUpdateTrigger(object):

    """Implementation of the 'deviceLevelUpdateTrigger' model.

    Attributes:
        trigger_id (str): The system assigned UUID of the trigger
        trigger_name (str): The user defined name of the trigger
        ecpd_id (str): The Enterprise Customer Profile Database ID
        trigger_category (TriggerCategoryEnum): The type of trigger being
            created or modified
        data_trigger (DataTrigger2): The model property of type DataTrigger2.
        notification (Notificationarray): The model property of type
            Notificationarray.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "trigger_id": 'triggerId',
        "trigger_name": 'triggerName',
        "ecpd_id": 'ecpdId',
        "trigger_category": 'triggerCategory',
        "data_trigger": 'dataTrigger',
        "notification": 'notification'
    }

    _optionals = [
        'trigger_id',
        'trigger_name',
        'ecpd_id',
        'trigger_category',
        'data_trigger',
        'notification',
    ]

    def __init__(self,
                 trigger_id=APIHelper.SKIP,
                 trigger_name=APIHelper.SKIP,
                 ecpd_id=APIHelper.SKIP,
                 trigger_category=APIHelper.SKIP,
                 data_trigger=APIHelper.SKIP,
                 notification=APIHelper.SKIP):
        """Constructor for the DeviceLevelUpdateTrigger class"""

        # Initialize members of the class
        if trigger_id is not APIHelper.SKIP:
            self.trigger_id = trigger_id 
        if trigger_name is not APIHelper.SKIP:
            self.trigger_name = trigger_name 
        if ecpd_id is not APIHelper.SKIP:
            self.ecpd_id = ecpd_id 
        if trigger_category is not APIHelper.SKIP:
            self.trigger_category = trigger_category 
        if data_trigger is not APIHelper.SKIP:
            self.data_trigger = data_trigger 
        if notification is not APIHelper.SKIP:
            self.notification = notification 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        trigger_id = dictionary.get("triggerId") if dictionary.get("triggerId") else APIHelper.SKIP
        trigger_name = dictionary.get("triggerName") if dictionary.get("triggerName") else APIHelper.SKIP
        ecpd_id = dictionary.get("ecpdId") if dictionary.get("ecpdId") else APIHelper.SKIP
        trigger_category = dictionary.get("triggerCategory") if dictionary.get("triggerCategory") else APIHelper.SKIP
        data_trigger = DataTrigger2.from_dictionary(dictionary.get('dataTrigger')) if 'dataTrigger' in dictionary.keys() else APIHelper.SKIP
        notification = Notificationarray.from_dictionary(dictionary.get('notification')) if 'notification' in dictionary.keys() else APIHelper.SKIP
        # Return an object of this model
        return cls(trigger_id,
                   trigger_name,
                   ecpd_id,
                   trigger_category,
                   data_trigger,
                   notification)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'trigger_id={(self.trigger_id if hasattr(self, "trigger_id") else None)!r}, '
                f'trigger_name={(self.trigger_name if hasattr(self, "trigger_name") else None)!r}, '
                f'ecpd_id={(self.ecpd_id if hasattr(self, "ecpd_id") else None)!r}, '
                f'trigger_category={(self.trigger_category if hasattr(self, "trigger_category") else None)!r}, '
                f'data_trigger={(self.data_trigger if hasattr(self, "data_trigger") else None)!r}, '
                f'notification={(self.notification if hasattr(self, "notification") else None)!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'trigger_id={(self.trigger_id if hasattr(self, "trigger_id") else None)!s}, '
                f'trigger_name={(self.trigger_name if hasattr(self, "trigger_name") else None)!s}, '
                f'ecpd_id={(self.ecpd_id if hasattr(self, "ecpd_id") else None)!s}, '
                f'trigger_category={(self.trigger_category if hasattr(self, "trigger_category") else None)!s}, '
                f'data_trigger={(self.data_trigger if hasattr(self, "data_trigger") else None)!s}, '
                f'notification={(self.notification if hasattr(self, "notification") else None)!s})')
