# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from verizon.api_helper import APIHelper
from verizon.models.devicepropertyselection import Devicepropertyselection


class Devicepropertyfilter(object):

    """Implementation of the 'devicepropertyfilter' model.

    Attributes:
        selection (Devicepropertyselection): The model property of type
            Devicepropertyselection.
        querytotalcount (bool): The model property of type bool.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "selection": '$selection',
        "querytotalcount": '$querytotalcount'
    }

    _optionals = [
        'selection',
        'querytotalcount',
    ]

    def __init__(self,
                 selection=APIHelper.SKIP,
                 querytotalcount=APIHelper.SKIP):
        """Constructor for the Devicepropertyfilter class"""

        # Initialize members of the class
        if selection is not APIHelper.SKIP:
            self.selection = selection 
        if querytotalcount is not APIHelper.SKIP:
            self.querytotalcount = querytotalcount 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        selection = Devicepropertyselection.from_dictionary(dictionary.get('$selection')) if '$selection' in dictionary.keys() else APIHelper.SKIP
        querytotalcount = dictionary.get("$querytotalcount") if "$querytotalcount" in dictionary.keys() else APIHelper.SKIP
        # Return an object of this model
        return cls(selection,
                   querytotalcount)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'selection={(self.selection if hasattr(self, "selection") else None)!r}, '
                f'querytotalcount={(self.querytotalcount if hasattr(self, "querytotalcount") else None)!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'selection={(self.selection if hasattr(self, "selection") else None)!s}, '
                f'querytotalcount={(self.querytotalcount if hasattr(self, "querytotalcount") else None)!s})')
