# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class DevicesProtocolEnum(object):

    """Implementation of the 'DevicesProtocol' enum.

    Firmware protocol. Valid values include: LWM2M, OMADM, HTTP.

    Attributes:
        LWM2M: The enum member of type str.
        OMDADM: The enum member of type str.
        HTTP: The enum member of type str.

    """
    LW_M2M = 'LWM2M'

    OMDADM = 'OMDADM'

    HTTP = 'HTTP'

