# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class DistributionTypesEnum(object):

    """Implementation of the 'DistributionTypes' enum.

    The distribution types:
      - Targeted: Generate targeted messages to the road users that are
    affected by the zone rules
      - Broadcast: Broadcast messages to regions based on the Geofence.

    Attributes:
        TARGETED: The enum member of type str.
        BROADCAST: The enum member of type str.

    """
    TARGETED = 'Targeted'

    BROADCAST = 'Broadcast'

