# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from verizon.api_helper import APIHelper
from verizon.models.dto_sensor_boarding_event import DtoSensorBoardingEvent


class DtoSensorOffBoardingStatusResponse(object):

    """Implementation of the 'dto.SensorOffBoardingStatusResponse' model.

    Attributes:
        events (List[DtoSensorBoardingEvent]): The model property of type
            List[DtoSensorBoardingEvent].
        isstillregistered (bool): The model property of type bool.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "events": 'events',
        "isstillregistered": 'isstillregistered'
    }

    _optionals = [
        'events',
        'isstillregistered',
    ]

    def __init__(self,
                 events=APIHelper.SKIP,
                 isstillregistered=APIHelper.SKIP):
        """Constructor for the DtoSensorOffBoardingStatusResponse class"""

        # Initialize members of the class
        if events is not APIHelper.SKIP:
            self.events = events 
        if isstillregistered is not APIHelper.SKIP:
            self.isstillregistered = isstillregistered 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        events = None
        if dictionary.get('events') is not None:
            events = [DtoSensorBoardingEvent.from_dictionary(x) for x in dictionary.get('events')]
        else:
            events = APIHelper.SKIP
        isstillregistered = dictionary.get("isstillregistered") if "isstillregistered" in dictionary.keys() else APIHelper.SKIP
        # Return an object of this model
        return cls(events,
                   isstillregistered)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'events={(self.events if hasattr(self, "events") else None)!r}, '
                f'isstillregistered={(self.isstillregistered if hasattr(self, "isstillregistered") else None)!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'events={(self.events if hasattr(self, "events") else None)!s}, '
                f'isstillregistered={(self.isstillregistered if hasattr(self, "isstillregistered") else None)!s})')
