# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from verizon.api_helper import APIHelper
from verizon.models.sensor_insights_ble import SensorInsightsBLE


class DtoDeviceConfig(object):

    """Implementation of the 'dto.deviceConfig' model.

    Attributes:
        ble (SensorInsightsBLE): Property objects for Bluetooth Low-Energy
            (BLE) devices

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "ble": 'ble'
    }

    _optionals = [
        'ble',
    ]

    def __init__(self,
                 ble=APIHelper.SKIP):
        """Constructor for the DtoDeviceConfig class"""

        # Initialize members of the class
        if ble is not APIHelper.SKIP:
            self.ble = ble 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        ble = SensorInsightsBLE.from_dictionary(dictionary.get('ble')) if 'ble' in dictionary.keys() else APIHelper.SKIP
        # Return an object of this model
        return cls(ble)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'ble={(self.ble if hasattr(self, "ble") else None)!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'ble={(self.ble if hasattr(self, "ble") else None)!s})')
