# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from verizon.api_helper import APIHelper
from verizon.models.dto_device_config import DtoDeviceConfig


class DtoDeviceActionSetConfiguration(object):

    """Implementation of the 'dto.DeviceActionSetConfiguration' model.

    Attributes:
        device_config (DtoDeviceConfig): The model property of type
            DtoDeviceConfig.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "device_config": 'deviceConfig'
    }

    _optionals = [
        'device_config',
    ]

    def __init__(self,
                 device_config=APIHelper.SKIP):
        """Constructor for the DtoDeviceActionSetConfiguration class"""

        # Initialize members of the class
        if device_config is not APIHelper.SKIP:
            self.device_config = device_config 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        device_config = DtoDeviceConfig.from_dictionary(dictionary.get('deviceConfig')) if 'deviceConfig' in dictionary.keys() else APIHelper.SKIP
        # Return an object of this model
        return cls(device_config)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'device_config={(self.device_config if hasattr(self, "device_config") else None)!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'device_config={(self.device_config if hasattr(self, "device_config") else None)!s})')
