# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from verizon.api_helper import APIHelper
from verizon.models.dto_sensor_boarding_event import DtoSensorBoardingEvent


class DtoSensorOnBoardingStatusResponse(object):

    """Implementation of the 'dto.SensorOnBoardingStatusResponse' model.

    Attributes:
        events (List[DtoSensorBoardingEvent]): The model property of type
            List[DtoSensorBoardingEvent].

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "events": 'events'
    }

    _optionals = [
        'events',
    ]

    def __init__(self,
                 events=APIHelper.SKIP):
        """Constructor for the DtoSensorOnBoardingStatusResponse class"""

        # Initialize members of the class
        if events is not APIHelper.SKIP:
            self.events = events 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        events = None
        if dictionary.get('events') is not None:
            events = [DtoSensorBoardingEvent.from_dictionary(x) for x in dictionary.get('events')]
        else:
            events = APIHelper.SKIP
        # Return an object of this model
        return cls(events)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'events={(self.events if hasattr(self, "events") else None)!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'events={(self.events if hasattr(self, "events") else None)!s})')
