# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ETXNetworkTypeEnum(object):

    """Implementation of the 'ETXNetworkType' enum.

    The type of the device's network connection at the time of the request. If
    the device is on the Verizon cellular network it should use the "VZ" value
    otherwise the "non-VZ" value.
    Devices on the Verizon network can directly access the ETX Message
    Exchange on the MEC (Mobile Edge Compute server)

    Attributes:
        VZ: The enum member of type str.
        NONVZ: The enum member of type str.

    """
    VZ = 'VZ'

    NONVZ = 'non-VZ'

