# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ETXClientTypeEnum(object):

    """Implementation of the 'ETXClientType' enum.

    The type of the client that is to be registered. This is one of the major
    traffic participant groups considered in V2X communication. The system
    uses this value to define which topics the client will be able to publish
    and subscribe to.
    Values:
    - **Vehicle** - Vehicle with an enclosure around the passengers.
    (Subtypes: PassengerCar, Truck, Bus, EmergencyVehicle, SchoolBus,
    MaintenanceVehicle)
    - **VulnerableRoadUser** - Traffic participants without a protecting
    enclosure. (Subtypes: Motorcycle, Bicycle, Pedestrian, Scooter)
    - **TrafficLightController** - A Traffic light controller system.
    (Subtypes: NA)
    - **InfrastructureSensor** - Sensors that are deployed in the
    infrastructure. (Subtypes: RoadSideUnit, Camera, Lidar, Radar,
    InductiveLoop, MagneticSensor)
    - **OnboardSensor** - Sensors that are onboard on a vehicle(Subtypes:
    Camera, Lidar, Radar)
    - **Software** - A software system or application. (Subtypes: Platform,
    Application, NA)

    Attributes:
        VEHICLE: The enum member of type str.
        VULNERABLEROADUSER: The enum member of type str.
        TRAFFICLIGHTCONTROLLER: The enum member of type str.
        INFRASTRUCTURESENSOR: The enum member of type str.
        ONBOARDSENSOR: The enum member of type str.
        SOFTWARE: The enum member of type str.

    """
    VEHICLE = 'Vehicle'

    VULNERABLEROADUSER = 'VulnerableRoadUser'

    TRAFFICLIGHTCONTROLLER = 'TrafficLightController'

    INFRASTRUCTURESENSOR = 'InfrastructureSensor'

    ONBOARDSENSOR = 'OnboardSensor'

    SOFTWARE = 'Software'

