# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class FeatureCollectionTypeEnum(object):

    """Implementation of the 'FeatureCollectionType' enum.

    Attributes:
        FEATURECOLLECTION: The enum member of type str.

    """
    FEATURECOLLECTION = 'FeatureCollection'

