# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from verizon.api_helper import APIHelper


class FilterCriteria1(object):

    """Implementation of the 'FilterCriteria1' model.

    Attributes:
        carrier_service_plan_code (str): The model property of type str.
        account_name_list (List[str]): An array of account names

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "carrier_service_plan_code": 'carrierServicePlanCode',
        "account_name_list": 'accountNameList'
    }

    _optionals = [
        'carrier_service_plan_code',
        'account_name_list',
    ]

    def __init__(self,
                 carrier_service_plan_code=APIHelper.SKIP,
                 account_name_list=APIHelper.SKIP):
        """Constructor for the FilterCriteria1 class"""

        # Initialize members of the class
        if carrier_service_plan_code is not APIHelper.SKIP:
            self.carrier_service_plan_code = carrier_service_plan_code 
        if account_name_list is not APIHelper.SKIP:
            self.account_name_list = account_name_list 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        carrier_service_plan_code = dictionary.get("carrierServicePlanCode") if dictionary.get("carrierServicePlanCode") else APIHelper.SKIP
        account_name_list = dictionary.get("accountNameList") if dictionary.get("accountNameList") else APIHelper.SKIP
        # Return an object of this model
        return cls(carrier_service_plan_code,
                   account_name_list)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'carrier_service_plan_code={(self.carrier_service_plan_code if hasattr(self, "carrier_service_plan_code") else None)!r}, '
                f'account_name_list={(self.account_name_list if hasattr(self, "account_name_list") else None)!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'carrier_service_plan_code={(self.carrier_service_plan_code if hasattr(self, "carrier_service_plan_code") else None)!s}, '
                f'account_name_list={(self.account_name_list if hasattr(self, "account_name_list") else None)!s})')
