# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class FirmwareProtocolEnum(object):

    """Implementation of the 'FirmwareProtocol' enum.

    Firmware protocol. Valid values include: LWM2M, OMD-DM, all.

    Attributes:
        LWM2M: The enum member of type str.
        OMDDM: The enum member of type str.
        ALL: The enum member of type str.

    """
    LW_M2M = 'LWM2M'

    OMDDM = 'OMD-DM'

    ALL = 'all'

