# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class FirmwareTypeListEnum(object):

    """Implementation of the 'FirmwareTypeList' enum.

    Possible values are `append` or `remove`

    Attributes:
        APPEND: The enum member of type str.
        REMOVE: The enum member of type str.

    """
    APPEND = 'append'

    REMOVE = 'remove'

