# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class FrameTypeEnum(object):

    """Implementation of the 'FrameType' enum.

    The frameType data element provides the type of message to follow in the
    rest of the message frame structure. The following frame types are
    supported:
     - unknown
     - advisory
     - roadSignage
     - commercialSignage

    Attributes:
        UNKNOWN: The enum member of type str.
        ADVISORY: The enum member of type str.
        ROADSIGNAGE: The enum member of type str.
        COMMERCIALSIGNAGE: The enum member of type str.

    """
    UNKNOWN = 'unknown'

    ADVISORY = 'advisory'

    ROADSIGNAGE = 'roadSignage'

    COMMERCIALSIGNAGE = 'commercialSignage'

