# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from verizon.models.offset_system import OffsetSystem


class GeographicalPathDescription(object):

    """Implementation of the 'GeographicalPathDescription' model.

    This data frame can describe a complex path of arbitrary size using node
    offset method (LL offsets).

    Attributes:
        path (OffsetSystem): The OffsetSystem data frame selects a sequence of
            node offsets described in the Lat-Long offset method.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "path": 'path'
    }

    def __init__(self,
                 path=None):
        """Constructor for the GeographicalPathDescription class"""

        # Initialize members of the class
        self.path = path 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        path = OffsetSystem.from_dictionary(dictionary.get('path')) if dictionary.get('path') else None
        # Return an object of this model
        return cls(path)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'path={self.path!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'path={self.path!s})')
