# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class Geolocation(object):

    """Implementation of the 'Geolocation' model.

    Geolocation of the device at the time of the connection request in GPS
    coordinates.

    Attributes:
        latitude (float): The GPS Latitude value
        longitude (float): The GPS Longitude value

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "latitude": 'Latitude',
        "longitude": 'Longitude'
    }

    def __init__(self,
                 latitude=None,
                 longitude=None):
        """Constructor for the Geolocation class"""

        # Initialize members of the class
        self.latitude = latitude 
        self.longitude = longitude 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        latitude = dictionary.get("Latitude") if dictionary.get("Latitude") else None
        longitude = dictionary.get("Longitude") if dictionary.get("Longitude") else None
        # Return an object of this model
        return cls(latitude,
                   longitude)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'latitude={self.latitude!r}, '
                f'longitude={self.longitude!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'latitude={self.latitude!s}, '
                f'longitude={self.longitude!s})')
