# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from verizon.api_helper import APIHelper
from verizon.models.m_5g_bidevice_id_1 import M5gBideviceId1


class M5gBideviceIdarray(object):

    """Implementation of the '5gbideviceIdarray' model.

    Attributes:
        device_id (List[M5gBideviceId1]): The model property of type
            List[M5gBideviceId1].

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "device_id": 'deviceId'
    }

    _optionals = [
        'device_id',
    ]

    def __init__(self,
                 device_id=APIHelper.SKIP):
        """Constructor for the M5gBideviceIdarray class"""

        # Initialize members of the class
        if device_id is not APIHelper.SKIP:
            self.device_id = device_id 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        device_id = None
        if dictionary.get('deviceId') is not None:
            device_id = [M5gBideviceId1.from_dictionary(x) for x in dictionary.get('deviceId')]
        else:
            device_id = APIHelper.SKIP
        # Return an object of this model
        return cls(device_id)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'device_id={(self.device_id if hasattr(self, "device_id") else None)!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'device_id={(self.device_id if hasattr(self, "device_id") else None)!s})')
