# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class MECPlatformStatusEnum(object):

    """Implementation of the 'MECPlatformStatus' enum.

    Status of the MEC Platform (default is 'unknown')

    Attributes:
        ACTIVE: The enum member of type str.
        INACTIVE: The enum member of type str.
        UNKNOWN: The enum member of type str.

    """
    ACTIVE = 'Active'

    INACTIVE = 'Inactive'

    UNKNOWN = 'unknown'

