# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ModeEnum(object):

    """Implementation of the 'Mode' enum.

    the reporting mode of the tilt sensor

    Attributes:
        REPORTONCHANGE: The enum member of type str.

    """
    REPORTONCHANGE = 'reportOnChange'

