# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class MultiLineStringTypeEnum(object):

    """Implementation of the 'MultiLineStringType' enum.

    Attributes:
        MULTILINESTRING: The enum member of type str.

    """
    MULTILINESTRING = 'MultiLineString'

