# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from verizon.models.node_l_lm_d_64_b import NodeLLmD64b


class NodeOffsetPointLL(object):

    """Implementation of the 'NodeOffsetPointLL' model.

    The NodeOffsetPointLL data frame presents a structure to hold 64 bits
    sized data frames for a single node geometry path. Nodes are described in
    terms of latitude and longitude.

    Attributes:
        node_lat_lon (NodeLLmD64b): A 64-bit node type with lat-long values
            expressed in standard SAE 1/10th of a microdegree.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "node_lat_lon": 'nodeLatLon'
    }

    def __init__(self,
                 node_lat_lon=None):
        """Constructor for the NodeOffsetPointLL class"""

        # Initialize members of the class
        self.node_lat_lon = node_lat_lon 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        node_lat_lon = NodeLLmD64b.from_dictionary(dictionary.get('nodeLatLon')) if dictionary.get('nodeLatLon') else None
        # Return an object of this model
        return cls(node_lat_lon)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'node_lat_lon={self.node_lat_lon!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'node_lat_lon={self.node_lat_lon!s})')
