# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class NumericalDataUnitEnum(object):

    """Implementation of the 'NumericalDataUnit' enum.

    Unit of time.

    Attributes:
        SECOND: The enum member of type str.
        MINUTE: The enum member of type str.
        HOUR: The enum member of type str.
        DAY: The enum member of type str.

    """
    SECOND = 'SECOND'

    MINUTE = 'MINUTE'

    HOUR = 'HOUR'

    DAY = 'DAY'

