# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from verizon.models.offset import Offset


class OffsetSystem(object):

    """Implementation of the 'OffsetSystem' model.

    The OffsetSystem data frame selects a sequence of node offsets described
    in the Lat-Long offset method.

    Attributes:
        offset (Offset): The sequence of node offsets then describes a path or
            polygon in the Lat-Long system.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "offset": 'offset'
    }

    def __init__(self,
                 offset=None):
        """Constructor for the OffsetSystem class"""

        # Initialize members of the class
        self.offset = offset 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        offset = Offset.from_dictionary(dictionary.get('offset')) if dictionary.get('offset') else None
        # Return an object of this model
        return cls(offset)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'offset={self.offset!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'offset={self.offset!s})')
