# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from verizon.models.node_list_ll import NodeListLL


class Offset(object):

    """Implementation of the 'Offset' model.

    The sequence of node offsets then describes a path or polygon in the
    Lat-Long system.

    Attributes:
        ll (NodeListLL): The NodeListLL data structure provides the sequence
            of signed offset node point values for determining the latitude
            and longitude. Each LL point is referred to as a node point.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "ll": 'll'
    }

    def __init__(self,
                 ll=None):
        """Constructor for the Offset class"""

        # Initialize members of the class
        self.ll = ll 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        ll = NodeListLL.from_dictionary(dictionary.get('ll')) if dictionary.get('ll') else None
        # Return an object of this model
        return cls(ll)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'll={self.ll!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'll={self.ll!s})')
