# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from verizon.api_helper import APIHelper
from verizon.models.resource_on_board_sensor import ResourceOnBoardSensor


class Payload(object):

    """Implementation of the 'Payload' model.

    Attributes:
        addsensor (ResourceOnBoardSensor): The model property of type
            ResourceOnBoardSensor.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "addsensor": 'addsensor'
    }

    _optionals = [
        'addsensor',
    ]

    def __init__(self,
                 addsensor=APIHelper.SKIP):
        """Constructor for the Payload class"""

        # Initialize members of the class
        if addsensor is not APIHelper.SKIP:
            self.addsensor = addsensor 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        addsensor = ResourceOnBoardSensor.from_dictionary(dictionary.get('addsensor')) if 'addsensor' in dictionary.keys() else APIHelper.SKIP
        # Return an object of this model
        return cls(addsensor)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'addsensor={(self.addsensor if hasattr(self, "addsensor") else None)!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'addsensor={(self.addsensor if hasattr(self, "addsensor") else None)!s})')
