# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class PolygonTypeEnum(object):

    """Implementation of the 'PolygonType' enum.

    Attributes:
        POLYGON: The enum member of type str.

    """
    POLYGON = 'Polygon'

