# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ProvisioningStatusFilterEnum(object):

    """Implementation of the 'ProvisioningStatusFilter' enum.

    The last status of the device as a list filter.

    Attributes:
        UNKNOWN: The enum member of type str.
        DEACTIVATED: The enum member of type str.
        ACTIVATED: The enum member of type str.
        DEACTIVE: The enum member of type str.
        ACTIVE: The enum member of type str.
        SUSPEND: The enum member of type str.
        PENDING_ACTIVATION: The enum member of type str.
        PENDING_DEACTIVATION: The enum member of type str.
        PRE_ACTIVE: The enum member of type str.
        ACTIVATION_READY: The enum member of type str.
        INVENTORY: The enum member of type str.
        PURGED: The enum member of type str.
        REPLACED: The enum member of type str.
        RETIRED: The enum member of type str.
        TEST_READY: The enum member of type str.

    """
    UNKNOWN = 'UNKNOWN'

    DEACTIVATED = 'DEACTIVATED'

    ACTIVATED = 'ACTIVATED'

    DEACTIVE = 'DEACTIVE'

    ACTIVE = 'ACTIVE'

    SUSPEND = 'SUSPEND'

    PENDING_ACTIVATION = 'PENDING_ACTIVATION'

    PENDING_DEACTIVATION = 'PENDING_DEACTIVATION'

    PRE_ACTIVE = 'PRE_ACTIVE'

    ACTIVATION_READY = 'ACTIVATION_READY'

    INVENTORY = 'INVENTORY'

    PURGED = 'PURGED'

    REPLACED = 'REPLACED'

    RETIRED = 'RETIRED'

    TEST_READY = 'TEST_READY'

