# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from verizon.api_helper import APIHelper
from verizon.models.rate_plan_group import RatePlanGroup


class Rateplan(object):

    """Implementation of the 'rateplan' model.

    Attributes:
        rate_plan_group (List[RatePlanGroup]): An array of rate plan group
            names

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "rate_plan_group": 'ratePlanGroup'
    }

    _optionals = [
        'rate_plan_group',
    ]

    def __init__(self,
                 rate_plan_group=APIHelper.SKIP):
        """Constructor for the Rateplan class"""

        # Initialize members of the class
        if rate_plan_group is not APIHelper.SKIP:
            self.rate_plan_group = rate_plan_group 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        rate_plan_group = None
        if dictionary.get('ratePlanGroup') is not None:
            rate_plan_group = [RatePlanGroup.from_dictionary(x) for x in dictionary.get('ratePlanGroup')]
        else:
            rate_plan_group = APIHelper.SKIP
        # Return an object of this model
        return cls(rate_plan_group)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'rate_plan_group={(self.rate_plan_group if hasattr(self, "rate_plan_group") else None)!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'rate_plan_group={(self.rate_plan_group if hasattr(self, "rate_plan_group") else None)!s})')
