# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class RequestStatusEnum(object):

    """Implementation of the 'RequestStatus' enum.

    The current status of the callback response.

    Attributes:
        PENDING: The enum member of type str.
        SUCCESS: The enum member of type str.
        FAILURE: The enum member of type str.

    """
    PENDING = 'Pending'

    SUCCESS = 'Success'

    FAILURE = 'Failure'

