# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from verizon.api_helper import APIHelper
from verizon.models.devicepropertyfilter import Devicepropertyfilter


class ResourceResourceQuery(object):

    """Implementation of the 'resource.resourceQuery' model.

    Attributes:
        filter (Devicepropertyfilter): The model property of type
            Devicepropertyfilter.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "filter": 'filter'
    }

    _optionals = [
        'filter',
    ]

    def __init__(self,
                 filter=APIHelper.SKIP):
        """Constructor for the ResourceResourceQuery class"""

        # Initialize members of the class
        if filter is not APIHelper.SKIP:
            self.filter = filter 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        filter = Devicepropertyfilter.from_dictionary(dictionary.get('filter')) if 'filter' in dictionary.keys() else APIHelper.SKIP
        # Return an object of this model
        return cls(filter)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'filter={(self.filter if hasattr(self, "filter") else None)!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'filter={(self.filter if hasattr(self, "filter") else None)!s})')
