# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ResponseCodeEnum(object):

    """Implementation of the 'ResponseCode' enum.

    Possible response codes.

    Attributes:
        INVALID_ACCESS: The enum member of type str.
        INVALID_PARAMETER: The enum member of type str.
        INTERNAL_ERROR: The enum member of type str.
        SUCCESS: The enum member of type str.

    """
    INVALID_ACCESS = 'INVALID_ACCESS'

    INVALID_PARAMETER = 'INVALID_PARAMETER'

    INTERNAL_ERROR = 'INTERNAL_ERROR'

    SUCCESS = 'SUCCESS'

