# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class RulesCycleTypeEnum(object):

    """Implementation of the 'rulesCycleType' enum.

    The interval to monitor for the threshold. This can be Daily, Weekly or
    Monthly

    Attributes:
        DAILY: The enum member of type str.
        WEEKLY: The enum member of type str.
        MONTHLY: The enum member of type str.

    """
    DAILY = 'Daily'

    WEEKLY = 'Weekly'

    MONTHLY = 'Monthly'

