# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ServiceNameEnum(object):

    """Implementation of the 'serviceName' enum.

    Service name

    Attributes:
        LOCATION: The enum member of type str.
        FOTA: The enum member of type str.

    """
    LOCATION = 'Location'

    FOTA = 'fota'

