# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ThresholdUnitEnum(object):

    """Implementation of the 'thresholdUnit' enum.

    The units of the threshold. This can be KB, Kilobits, MB, Megabits, or GB,
    Gigabits

    Attributes:
        KB: The enum member of type str.
        MB: The enum member of type str.
        GB: The enum member of type str.

    """
    KB = 'KB'

    MB = 'MB'

    GB = 'GB'

