# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class TriggerCategoryEnum(object):

    """Implementation of the 'triggerCategory' enum.

    The type of trigger being created or modified

    Attributes:
        ACCOUNTUSAGE: The enum member of type str.
        DEVICEGROUPUSAGE: The enum member of type str.
        PRICEPLANDATAUSAGE: The enum member of type str.

    """
    ACCOUNTUSAGE = 'AccountUsage'

    DEVICEGROUPUSAGE = 'DeviceGroupUsage'

    PRICEPLANDATAUSAGE = 'PricePlanDataUsage'

