# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from verizon.api_helper import APIHelper


class Tscore(object):

    """Implementation of the 'Tscore' model.

    Attributes:
        profileid (str): the UUID of the profile
        profileversionid (str): the UUID of the profile version

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "profileid": 'profileid',
        "profileversionid": 'profileversionid'
    }

    _optionals = [
        'profileid',
        'profileversionid',
    ]

    def __init__(self,
                 profileid=APIHelper.SKIP,
                 profileversionid=APIHelper.SKIP):
        """Constructor for the Tscore class"""

        # Initialize members of the class
        if profileid is not APIHelper.SKIP:
            self.profileid = profileid 
        if profileversionid is not APIHelper.SKIP:
            self.profileversionid = profileversionid 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        profileid = dictionary.get("profileid") if dictionary.get("profileid") else APIHelper.SKIP
        profileversionid = dictionary.get("profileversionid") if dictionary.get("profileversionid") else APIHelper.SKIP
        # Return an object of this model
        return cls(profileid,
                   profileversionid)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'profileid={(self.profileid if hasattr(self, "profileid") else None)!r}, '
                f'profileversionid={(self.profileversionid if hasattr(self, "profileversionid") else None)!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'profileid={(self.profileid if hasattr(self, "profileid") else None)!s}, '
                f'profileversionid={(self.profileversionid if hasattr(self, "profileversionid") else None)!s})')
