# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class UnitEnum(object):

    """Implementation of the 'Unit' enum.

    Attributes:
        MINUTES: The enum member of type str.
        HOURS: The enum member of type str.

    """
    MINUTES = 'minutes'

    HOURS = 'hours'

