# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class UpgradeStatusEnum(object):

    """Implementation of the 'UpgradeStatus' enum.

    The status of the upgrades that you want to retrieve.

    Attributes:
        REQUESTPENDING: The enum member of type str.
        QUEUED: The enum member of type str.
        REQUESTFAILED: The enum member of type str.
        INPROGRESS: The enum member of type str.
        FINISHED: The enum member of type str.
        UPGRADEFAILED: The enum member of type str.

    """
    REQUESTPENDING = 'RequestPending'

    QUEUED = 'Queued'

    REQUESTFAILED = 'RequestFailed'

    INPROGRESS = 'InProgress'

    FINISHED = 'Finished'

    UPGRADEFAILED = 'UpgradeFailed'

