# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

from apimatic_core.authentication.header_auth import HeaderAuth


class SessionToken(HeaderAuth):

    @property
    def error_message(self):
        """Display error message on occurrence of authentication failure
        in SessionToken

        """
        return "SessionToken: SessionToken is undefined."

    def __init__(self, session_token_credentials):
        auth_params = {}
        if session_token_credentials is not None \
                and session_token_credentials.session_token is not None:
            auth_params["SessionToken"] = session_token_credentials.session_token
        super().__init__(auth_params=auth_params)


class SessionTokenCredentials:

    @property
    def session_token(self):
        return self._session_token

    def __init__(self, session_token):
        if session_token is None:
            raise ValueError('session_token cannot be None')
        self._session_token = session_token

    def clone_with(self, session_token=None):
        return SessionTokenCredentials(session_token or self.session_token)
